### ISSUE TITLE
global-hotkey lacks support for wayland compositors and panics on startup when attempting to register the hotkey

### ISSUE THREAD

**Issue by ioangogo** [timmo001/home-assistant-assist-desktop#15]
```
Cannot get default EGL display: EGL_BAD_PARAMETER
WaylandCompositor requires eglCreateImage and eglDestroyImage.
Nested Wayland compositor could not initialize EGL
thread 'main' panicked at src/main.rs:278:18:
failed to register Alt+A shortcut: GlobalShortcut(InvalidAccelerator("Unable to register global shortcut"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I feel like it would be better to not this app only supports x11 or allow the registration to fail and just run without shortcut support.

a properfix has to way till Tauri fixes this issue https://github.com/tauri-apps/global-hotkey/issues/28

**Comment by GrumpyMeow** [comment]
On my KDE desktop i get this error:
```
thread 'main' panicked at src/main.rs:292:18:
failed to register Alt+A shortcut: GlobalShortcut(InvalidAccelerator("Unable to register global shortcut"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
When i run it with `sudo home-assistant-assist`, it does work.
